language: python
os:
    - linux
python:
    - 3.8
before_script:
    #- sudo useradd -m qxqx
    #- sudo chown -R qxqx:qxqx /home/qxqx
    #- su qxqx
    - mkdir /home/${USER}/.config
    - mkdir /home/${USER}/.config/nvim
    - openssl aes-256-cbc -K $encrypted_54b4dd754176_key -iv $encrypted_54b4dd754176_iv
      -in .travis/gitee_id_rsa.enc -out ~/.ssh/gitee_id_rsa -d
    #- openssl aes-256-cbc -K $encrypted_54b4dd754176_key -iv $encrypted_54b4dd754176_iv
      #-in .travis/github_id_rsa.enc -out ~/.ssh/github_id_rsa -d
    - chmod 600 ~/.ssh/gitee_id_rsa
    - eval $(ssh-agent)
    - ssh-add ~/.ssh/gitee_id_rsa
    - cp .travis/ssh_config ~/.ssh/config
    - git config --global user.name "qiaoxiaoqianxi"
    - git config --global user.email "liminghua13118@163.com"
install: 
    - pip3 install requests
script:
    - python Copy.py
